export const SETTRAINLIST = 'TRAINLIST/SETTRAINLIST';
export const SSRGETTRAINLIST = 'TRAINLIST/SSRGETTRAINLIST';
export const FILTERSTATE = 'TRAINLIST/FILTERVISIBLESTATE';
export const ONLYTICKETS = 'TRAINLIST/ONLYTICKETS';
export const ORDERTYPE = 'TRAINLIST/ORDERTYPE';
export const FILTERDATA = 'TRAINLIST/FILTERDATA';

export const ASYNCSETTRAINLIST = 'ASYNC/TRAINLIST/SETTRAINLIST';