export const SETTRAININFORM = 'TRAINORDERFILL/SETTRAININFORM';
export const SETTICKETINFORM = 'TRAINORDERFILL/SETTICKETINFORM';
export const SETUSERINFORM = 'TRAINORDERFILL/SETUSERINFORM';
export const SETPHONENUMBER = 'TRAINORDERFILL/SETPHONENUMBER';
export const CHOICESETAS = 'TRAINORDERFILL/CHOICESETAS';

export const ASYNCGETTRAININFORM = 'TRAINORDERFILL/ASYNCGETTRAININFORM';