export const SETMOMENTTABLE = 'TRAINTICKET/SETMOMENTTABLE';
export const SETSEATLIST = 'TRAINTICKET/SETSEATLIST';
export const SETTRAININFORM = 'TRAINTICKET/SETTRAININFORM';
export const SETDEPARTDATE = 'TRAINTICKET/SETDEPARTDATE';
export const MOMENTTABLEVISIBALE = 'TRAINTICKET/MOMENTTABLEVISIBALE';

export const ASYNCSETTRAININFORM = 'TRAINTICKET/ASYNCSETTRAININFORM';