export const SETFROM = 'QUNARINDEX/SETFROM';
export const SETTO = 'QUNARINDEX/SETTO';
export const SETCITYSELECTORVISIBLE = 'QUNARINDEX/SETCITYSELECTORVISIBLE';
export const CURRENTSELECTINGLEFTCIFT = 'QUNARINDEX/CURRENTSELECTINGLEFTCIFT';
export const SETCITYDATE = 'QUNARINDEX/SETCITYDATE';
export const SETLOADINGCITYDATE = 'QUNARINDEX/SETLOADINGCITYDATE';
export const SETDATESELECTORVISIBLEDATE = 'QUNARINDEX/SETDATESELECTORVISIBLEDATE';
export const SETHIGHSPEED = 'QUNARINDEX/SETHIGHSPEED';
export const SETAPLHALIST = 'QUNARINDEX/SETAPLHALIST';
export const SETDEPARTDATE = 'QUNARINDEX/SETDEPARTDATE';

export const GETCITYDATA = 'QUNARINDEX/GETCITYDATA';
export const EXCHANGEFROMTO = 'QUNARINDEX/EXCHANGEFROMTO';